const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";
const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS";
const PRODUCT_SAVE_FAILED = "PRODUCT_SAVE_FAILED";

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAILED,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAILED,
  PRODUCT_SAVE_REQUEST,
  PRODUCT_SAVE_SUCCESS,
  PRODUCT_SAVE_FAILED
};
